# Generated by Django 3.2.14 on 2022-10-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slider'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-id'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='image_400_by_400',
            new_name='image_400_400',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='body',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='event_end_date',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='event_start_date',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='snippet',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='view_count',
        ),
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occasion', to='home.event'),
        ),
    ]
