# Generated by Django 3.2.14 on 2022-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20221028_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='status',
        ),
        migrations.AddField(
            model_name='gallery',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
