# Generated by Django 3.2.14 on 2022-11-12 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20221111_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-id'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
