# Generated by Django 3.2.14 on 2022-10-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', '---------'), ('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('full_name', models.CharField(max_length=400)),
                ('image_370_by_410', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(max_length=200)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('speech', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Priest',
                'verbose_name_plural': 'Priests',
            },
        ),
    ]
