# Generated by Django 3.2.14 on 2022-10-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', '---------'), ('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('category', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('', '---------'), ('Mass', 'Mass'), ('Celebration', 'Celebration')], max_length=15, null=True)),
                ('image_1024_by_300', models.ImageField(blank=True, null=True, upload_to='')),
                ('event_start_date', models.DateTimeField(blank=True, null=True)),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('cost', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('venue', models.TextField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=400, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=400, null=True)),
                ('website', models.CharField(blank=True, max_length=400, null=True)),
                ('email_organizer', models.EmailField(blank=True, max_length=100, null=True)),
                ('quote', models.TextField(blank=True, null=True)),
                ('quote_author', models.CharField(blank=True, max_length=400, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_start_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', '---------'), ('draft', 'Draft'), ('published', 'Published')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_big', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HomeImage',
                'verbose_name_plural': 'Home Images',
                'ordering': ['-id'],
            },
        ),
    ]
