# Generated by Django 3.2.14 on 2022-10-29 14:05

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name_plural': 'Advert Videos',
            },
        ),
    ]
