# Generated by Django 3.2.14 on 2022-11-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_advertvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimages',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homeimages',
            name='image_big',
        ),
        migrations.RemoveField(
            model_name='homeimages',
            name='slug',
        ),
    ]
